[package]
name = "pyramid_animation"
version = "0.1.0"
authors = ["Fredrik Noren <fredrik.jw.noren@gmail.com>"]

[dependencies]
time = "*"
cgmath = "0.2.0"

[dependencies.pyramid]
path = "../pyramid"
